#!/bin/bash

projRoot=$(pwd)

if [ "$1" = '--interp' ]; then
	cd app
	defAssets="-DASSETS_DIR=$projRoot/assets"
	defSoy="-DSOYS_DIR=$projRoot/static/soy"
	runner="runhaskell $defAssets $defSoy Main.hs"
else
	runner="./Main"
fi

$runner

