#!/bin/bash

projRoot=$(pwd)

if [ "$1" = '--interp' ]; then
	cd app
	runner="runhaskell -DASSETS_DIR=$projRoot/assets Main.hs"
else
	runner="./Main"
fi

$runner \
	--template-files="$projRoot/static/soy/todo.soy" \
	--template-files="$projRoot/static/soy/server.soy" \
	--assets-root="$projRoot/assets"

